name: WorldDB Bug Report
description: File a bug report for the WorldDB application
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - CatVine
  - soto-nicole
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Reproduction steps
      description: Please make sure to tell us each of the steps you took to trigger this bug. Were you running a specific query? What went wrong? What did you expect to happen?
      placeholder: Tell us as much detail as possible!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - latest (Default)
        - v0.1.0.6
        - v0.1.0.5
        - v0.1.0.4
        - v0.1.0.3
        - v0.1.0.2
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/soto-nicole/sem-coursework/blob/master/CodeOfConduct.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: |
        Thank you for submitting this bug report and helping us make our application better!
